### ISSUE TITLE
Error pop-up: Option 'finishings' has value '3' and cannot be edited

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/system-config-printer#122] opened 2018-10-17 17:08 UTC
The following bug report appeared at Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1780310

For some IPP printers appears an error pop-up with the message mentioned above (or similar message) when opening the printer properties dialog. It does not come to anything going wrong afterwards. There is only this dialog annoying the user with a message he does not understand.
A simple symptomatic fix would be to turn this error dialog into a debug message which appears in the terminal when running s-c-p with the `--debug` option. This should also be done when the actual cause of the bug gets fixed.
An actual fix would be to check s-c-p's compatibility with modern driverless IPP printers, for example supporting correctly all the attributes reported on a get-printer-attributes IPP request (IPP 2.x) and also taking into account that the options for driverless printing reported by IPP are NOT identical with the options in PPD files, even if the file is supplied by the printer's manufacturer.

**Comment by zdohnal** [comment] 2018-10-18 14:46
Hi Till,
I'm sorry, I am unable to reproduce the issue - I have old HP Officejet Pro 8500 at the office (even older HP printer at home...), which provides only 'finishings-supported' and 'finishing-default' attributes, both set to number 3, which is 'None'. 
I even tried to push forcefully different values of attributes or push only 'finishing' attribute into dictionary, which is gotten from getPrinterAttributes() method (defined in python-cups project), but without triggering the error message. I tried to open 'Printer properities' - which got into scope, where the error message can show - and 'View printer queue' - which the reporter said he used, at least IIUC.

@tillkamppeter , are you able to reproduce the issue? Then we can see the variables contents during debugging...

From what I see from code: attributes seems to be taken from printer by getPrinterAttributes() (even IPP 2.* ones), then got processed in cupshelpers/cupshelpers.py and divided into possible_attributes and other_attributes and in several object attributes. I thought this can be outcome of 'finishings' isn't in correct dictionary, but it seems it doesn't trigger the message too.

**Comment by petersilva** [comment] 2018-11-05 22:14
I´m on ubuntu 18.04 printing to a ricoh network printer, and I see this problem.

**Comment by zdohnal** [comment] 2018-11-06 13:11
@petersilva Would you mind debugging the issue then? Since I'm not able to reproduce it with my printer.

**Comment by galgalesh** [comment] 2018-11-08 14:29
I'm having the same issue, I can help debugging if you tell me what to do.

**Comment by zdohnal** [comment] 2018-11-09 12:47
@galgalesh Thank you! I don't know which debugger you use - I use pudb - https://documen.tician.de/pudb/starting.html .
For start I would like to see what is in 'attrs' variable in getAttributes() method in cupshelpers/cupshelpers.py (line 118) after calling getPrinterAttributes() and contents of self.other_attributes and self.possible_attributes at the end of getAttributes() method.
Then from printerproperities.py (about lines 1399) I would like to see contents of 'option' variable, when option.name is 'finishings', self.printer.attributes and self.printer.possible_attributes.
If you would like more info how to do it, feel free to ask. Thank you!

**Comment by galgalesh** [comment] 2018-11-09 15:41
@zdohnal 

I can see the value of these variables, but they are very big so they are cropped in the pudb UI. Is there an easy way for me to copy the full contents to clipboard or display it elsewhere?

![image](https://user-images.githubusercontent.com/1492981/48272180-5336b680-e43e-11e8-8338-3f0e67467940.png)

**Comment by zdohnal** [comment] 2018-11-12 15:21
Sorry, I don't know - but you can try to print out in python console in pudb UI and copy it from there (or use python commands to get variable contents) into some files, which you can attach here (they need to have .txt suffix to attach it here on github). I'm sorry for the inconvenience, and thank you again for helping me debugging!

**Comment by galgalesh** [comment] 2018-11-13 16:26
I did it with good-old print statements in the end. This didn't work for the `options` variable though, so I added screenshots for those. I have two printers that trow errors.

(note that the issue with "finishings" is in the second printer, the first printer has two other but similar errors.)

## Printer 1: a driverless printer that was automatically added

Logs: https://pastebin.com/ghyi2Kw6
Errors:
![image](https://user-images.githubusercontent.com/1492981/48426640-78d9fd80-e767-11e8-960a-7de2a7e01090.png)

![image](https://user-images.githubusercontent.com/1492981/48426663-8099a200-e767-11e8-9a3b-edfbf41fca87.png)

Value of `option` in debugger for `orientation-requested`:

![image](https://user-images.githubusercontent.com/1492981/48427098-54caec00-e768-11e8-9941-6cdedfdab710.png)

Value of `option` in debugger for `print-quality`:

![image](https://user-images.githubusercontent.com/1492981/48427400-ef2b2f80-e768-11e8-8934-70218c6f8117.png)



## Printer 2: a Ricoh Secure print queue configured with the ppd file supplied by ricoh

Logs: https://pastebin.com/mL8bWze6
Errors:
![image](https://user-images.githubusercontent.com/1492981/48426728-a0c96100-e767-11e8-80b2-bcac8e747bad.png)

![image](https://user-images.githubusercontent.com/1492981/48427298-bd19cd80-e768-11e8-80d4-fa6f839f4bf4.png)

**Comment by galgalesh** [comment] 2018-12-04 12:18
@zdohnal Did you manage to take a look at this yet?

**Comment by zdohnal** [comment] 2018-12-04 15:33
@galgalesh Sorry, not yet, other urgent issues on the plate... :(

**Comment by tillkamppeter** [comment] 2018-12-20 10:55
See also this Ubuntu bug report:
https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1766107

**Comment by zdohnal** [comment] 2019-01-03 09:15
I did a temporary fix for now as you suggested, please check commit 04ddf2fba0 . Hope, I'll get into more permanent solution in the future.

**Comment by tillkamppeter** [comment] 2019-01-07 19:10
Thank you very much for this temporary fix. I have applied it to the system-config-printer package of Ubuntu 19.04 (Disco) now.

**Comment by PorkCharsui79** [comment] 2019-02-19 14:19
I get the same error.
Linux Mint 19 Tara
system-config-printer=1.5.11-1ubuntu2 (from ubuntu bionic repo)
The temporary workaround from commit [04ddf2f](https://github.com/zdohnal/system-config-printer/commit/04ddf2fba0d9dd84c29430d688ceca1ae500885c) does get rid of the error message, but the setting remains unset.

**Comment by prlw1** [comment] 2019-02-26 16:30
Reached this bug as once again it was reproduced (ubuntu). (Remove label?)

**Comment by zdohnal** [comment] 2019-02-27 09:50
> (Remove label?)

The label is there because 'I' as upstream cannot reproduce it, because I do not have HW for it. IMO the label is correct, because I can only study logs of @galgalesh , who was so kind to provide debugging logs. To sum it up, it makes its fixing harder, because I cannot test it immediately....

**Comment by zdohnal** [comment] 2020-04-24 04:22
Temporary fixed in 1.5.12.

**Closed by zdohnal** 2020-04-24 04:22 UTC
Labels: Cannot reproduce, bug
