### ISSUE TITLE
Weird UI behavior when addprint off LAN using Ubuntu MATE 21.10

### ISSUE THREAD

**Issue by daniellasalle** [OpenPrinting/system-config-printer#248] opened 2021-11-10 22:05 UTC
When using a fully patched 21.10 system and adding a LAN printer via it's IP, the response is very weird. See enclosed picture.

PS: I believe this problem has been happening since AT LEAST 20.04.
---
ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu71
Architecture: amd64
CasperMD5CheckResult: unknown
CurrentDesktop: MATE
DistroRelease: Ubuntu 21.10
InstallationDate: Installed on 2020-08-29 (437 days ago)
InstallationMedia: Ubuntu-MATE 20.04.1 LTS "Focal Fossa" - Release amd64 (20200731)
Lpstat:
 device for _xeroxofficetq1_: ///dev/null
 device for C405: ///dev/null
 device for Xerox-CommonXCPT: socket://10.11.0.249:9100
MachineType: System manufacturer System Product Name
Package: system-config-printer 1.5.15-0ubuntu2
PackageArchitecture: all
Papersize: letter
PpdFiles:
 Error: command ['fgrep', '-H', '*NickName', '/etc/cups/ppd/Xerox-CommonXCPT.ppd', '/etc/cups/ppd/C405.ppd', '/etc/cups/ppd/_xeroxofficetq1_.ppd'] failed with exit code 2: grep: /etc/cups/ppd/Xerox-CommonXCPT.ppd: Permission denied
 grep: /etc/cups/ppd/C405.ppd: Permission denied
 grep: /etc/cups/ppd/_xeroxofficetq1_.ppd: Permission denied
ProcKernelCmdLine: BOOT_IMAGE=/vmlinuz-5.13.0-20-generic root=/dev/mapper/vgubuntu--mate-root ro quiet splash vt.handoff=7
ProcVersionSignature: Ubuntu 5.13.0-20.20-generic 5.13.14
RebootRequiredPkgs: Error: path contained symlinks.
Tags: impish
Uname: Linux 5.13.0-20-generic x86_64
UpgradeStatus: Upgraded to impish on 2021-10-14 (26 days ago)
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
_MarkForUpload: True
dmi.bios.date: 12/02/2020
dmi.bios.release: 5.17
dmi.bios.vendor: American Megatrends Inc.
dmi.bios.version: 5809
dmi.board.asset.tag: Default string
dmi.board.name: TUF X470-PLUS GAMING
dmi.board.vendor: ASUSTeK COMPUTER INC.
dmi.board.version: Rev X.0x
dmi.chassis.asset.tag: Default string
dmi.chassis.type: 3
dmi.chassis.vendor: Default string
dmi.chassis.version: Default string
dmi.modalias: dmi:bvnAmericanMegatrendsInc.:bvr5809:bd12/02/2020:br5.17:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:skuSKU:rvnASUSTeKCOMPUTERINC.:rnTUFX470-PLUSGAMING:rvrRevX.0x:cvnDefaultstring:ct3:cvrDefaultstring:
dmi.product.family: To be filled by O.E.M.
dmi.product.name: System Product Name
dmi.product.sku: SKU
dmi.product.version: System Version
dmi.sys.vendor: System manufacturer

**Comment by daniellasalle** [comment] 2021-11-10 22:05
![addprinter](https://user-images.githubusercontent.com/26171838/141201291-ee095f53-04e2-4371-8fbd-e84e23859109.png)

**Comment by zdohnal** [comment] 2021-11-11 07:25
Hi @daniellasalle ,

I can't reproduce the behavior - but those entries are supposed to be found network printers, it would be great if you could verify what's the output of ```lpinfo -l -v```.
Then please start system-config-printer with --debug option and start capturing logs like:

```
$ system-config-printer --debug &> log.txt
```

then go to the window where you see the issue and click on many entries (I need to see data which are under several entries to be have chance of understanding).

Then do close system-config-printer and attach the file here.

Thank you in advance!

**Comment by N0rbert** [comment] 2021-11-11 09:39
Downstream bug-report is at https://bugs.launchpad.net/bugs/1949654 .

**Comment by zdohnal** [comment] 2022-02-07 09:42
No reply for two months, closing.

**Closed by zdohnal** 2022-02-07 09:42 UTC
