### ISSUE TITLE
Translations are locked in Weblate

### ISSUE THREAD

**Issue by rffontenelle** [OpenPrinting/system-config-printer#238] opened 2021-09-20 10:57 UTC
The translation project in Fedora Weblate is locked due to issues, and is presenting some alerts. See https://translate.fedoraproject.org/projects/system-config-printer/master/#alerts

For your convenience,  I copied the alerts here:

## Could not merge the repository.

Weblate could not merge upstream changes while updating the repository.

```
First, rewinding head to replay your work on top of it...
Applying: Translated using Weblate (Russian)
warning: Cannot merge binary files: po/ru.po (HEAD vs. Translated using Weblate (Russian))
Using index info to reconstruct a base tree...
M	po/ru.po
Falling back to patching base and 3-way merge...
Auto-merging po/ru.po
CONFLICT (content): Merge conflict in po/ru.po
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 Translated using Weblate (Russian)

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

 (1)
```

**Typical workflow for fixing merge conflicts**

1. Commit all pending changes in Weblate and lock the translation component.

    ```wlc commit; wlc lock```

2. Add Weblate exported repository as a remote.<br>
    ```git remote add weblate https://translate.fedoraproject.org/git/system-config-printer/master/ ; git remote update weblate```
3. Merge Weblate changes and resolve any conflicts.<br>
    ```git merge weblate/main```
4. Push changes into upstream repository.<br>
    ```git push origin main```
5. Weblate should now be able to see updated repository and you can unlock it.<br>
    ```wlc pull ; wlc unlock```

[Check the FAQ for info on how to resolve this.](https://docs.weblate.org/en/weblate-4.8/faq.html#merge)

Appeared 5 days ago, last seen 5 days ago

## Broken repository browser URL

This component is set up incorrectly.

The repository browser URL points to non-existing locations:

*    https://github.com/OpenPrinting/system-config-printer/blob/master/../asyncipp.py#L473 (404 Client Error: Not Found for url: https://github.com/OpenPrinting/system-config-printer/blob/asyncipp.py#L473)

This can happen if the path within the translation files contains references to a parent directory, or is absolute.

Appeared a year ago, last seen 16 hours ago

**Comment by rffontenelle** [comment] 2021-09-20 10:59
Regard the "Broken repository browser URL", the browser URL should probably contain "po/" in its path to compensate the "..".

**Comment by zdohnal** [comment] 2021-09-21 06:08
Hi @rffontenelle ,

thanks for letting me know!

IMO these conflicts seem to happen when I merge the PR from weblate and someone has an old revision in weblate...
Anyway, I've merged the changes locally, but it seems I'm not able to unlock the repo (insufficient permissions :( I've written a ticket to admins about it). But IIRC it should get unlocked automatically after one day when there are no conflicts.

The browser URL warning will probably stay until I get a full access to the repo, but it is not a blocking warning.

I'll check tomorrow if it gets unlocked - if it is unlocked, I'll close the issue.

**Comment by zdohnal** [comment] 2021-09-23 04:33
@rffontenelle hmm, the project shows it is still locked, but there shouldn't be a conflict anymore... can you try

**Comment by rffontenelle** [comment] 2021-09-24 23:38
It doesn't look like it's going to unlock itself automatically, after waiting 2 days. I see that the "last seen" date isn't refreshing itself (it is just increasing, as if it was expecting an action).

Assuming the issue was solved, maybe it still requires `wlc unlock`?

**Comment by zdohnal** [comment] 2021-10-04 11:36
The problem is I cannot issue ```wlc unlock``` because apparently I don't have a permissions on the system-config-printer weblate project and the contact form doesn't seem to do the trick for contacting anyone which can help us.

I've written an email to trans@list.fedoraproject.org, maybe someone there can point me to the right direction.

**Comment by zdohnal** [comment] 2021-10-04 11:46
Yuri from the list unlocked the repo and gave me admin rights, and I'm able to push/lock/unlock translations now. And since I've seen you made changes already in weblate, IMO this issue can be closed :) .

**Closed by zdohnal** 2021-10-04 11:46 UTC

**Comment by rffontenelle** [comment] 2021-10-04 15:34
Indeed fixed. #240 already provides translations from Weblate. Thanks!
