### ISSUE TITLE
[abrt] system-config-printer: display_auth_info_dialog(): jobviewer.py:1115:display_auth_info_dialog:KeyError: 'auth-info-required'

### ISSUE THREAD

**Issue by brunobraga-hotmart** [OpenPrinting/system-config-printer#142] opened 2019-09-02 19:51 UTC
> Description of problem:
> Error trying to print...
> Print crash when try to open an authentication popup.
> 
> Version-Release number of selected component:
> system-config-printer-1.5.11-18.fc30
> 
> Additional info:
> reporter:       libreport-2.10.1
> cmdline:        /usr/bin/python3 /usr/share/system-config-printer/system-config-printer.py
> crash_function: display_auth_info_dialog
> exception_type: KeyError
> executable:     /usr/share/system-config-printer/system-config-printer.py
> interpreter:    python3-3.7.4-1.fc30.x86_64
> kernel:         5.2.9-200.fc30.x86_64
> runlevel:       N 5
> type:           Python3
> uid:            961205159
> 
> Truncated backtrace:
> jobviewer.py:1115:display_auth_info_dialog:KeyError: 'auth-info-required'
> 
> Traceback (most recent call last):
>   File "/usr/share/system-config-printer/jobviewer.py", line 1621, in on_job_authenticate_activate
>     uri, auth_info_required, True)
>   File "/usr/share/system-config-printer/jobviewer.py", line 1111, in get_authentication
>     self.display_auth_info_dialog (job, keyring_attrs)
>   File "/usr/share/system-config-printer/jobviewer.py", line 1115, in display_auth_info_dialog
>     auth_info_required = data['auth-info-required']
> KeyError: 'auth-info-required'
> 
> Local variables in innermost frame:
> self: <jobviewer.JobViewer object at 0x7f7e0e16fbe0 (jobviewer+JobViewer at 0x5607aa68dea0)>
> job: 5
> keyring_attrs: {'domain': '', 'server': '172.16.11.20', 'protocol': 'smb', 'uri': 'ipp://localhost/printers/minolta_konica', 'user': 'bruno.braga'}
> data: {'job-printer-uri': 'ipp://localhost/printers/minolta_konica', 'time-at-creation': 1567447377, 'job-state': 4, 'job-k-octets': 1, 'job-printer-name': 'minolta_konica', 'attributes-charset': 'utf-8', 'attributes-natural-language': 'en-us', 'device-uri': 'smb://172.16.11.20/minolta_konica', 'job-hold-until': 'auth-info-required', 'job-originating-user-name': 'bruno.braga', 'job-name': 'Test Page', '_status_text': 'Held for authentication'}

It seems a general problem.
Usage Scenario: user trying to print when an authentication is required. The authentication window is crashing.

It is found by me in Fedora and a similar problem was reported in CentOS:
https://bugzilla.redhat.com/show_bug.cgi?id=1748105
https://bugs.centos.org/view.php?id=16326

**Comment by brunobraga-hotmart** [comment] 2019-09-02 19:56
Sorry for dup. Open using a wrong user.
Could you delete that?

**Comment by tillkamppeter** [comment] 2019-09-02 19:59
Duplicate of issue #143, closing.

**Closed by tillkamppeter** 2019-09-02 19:59 UTC
